version: "3"
services:
  app:
    container_name: temp-obs
    build: .
    ports:
     - "8080:8080"
    links:
     - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - "./data:/data/db"
